dist: xenial
language: python
sudo: false

# Blacklist
branches:
  only:
    - master
python:
  - "3.6"
addons:
  apt:
    packages:
      - libgs-dev
before_install:
  - pip install -U pip jinja2 Pygments
script:
  - curl http://doxygen.nl/files/doxygen-1.8.15.linux.bin.tar.gz --output doxygen.tar.gz
  - tar xfv doxygen.tar.gz
  - PATH=$PATH:doxygen-1.8.15/bin
  - export PATH
  - git clone https://github.com/mosra/m.css.git
  - python m.css/documentation/doxygen.py Doxyfile-mcss
  #- doxygen Doxyfile.in
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
