# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - python3-pip

# Build your code e.g. by calling make
script:
  - pip3 --user install --upgrade pip
  - pip3 --user install Jinja2 Pygments
  - git clone https://github.com/mosra/m.css.git
  - doxygen Doxyfile.in

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
