language: python
sudo: false

# Blacklist
branches:
  only:
    - master
python:
  - "3.6"
addons:
  apt:
    packages:
      - doxygen
      - libgs-dev
before_install:
  - pip install -U pip jinja2 Pygments
script:
  - git clone https://github.com/mosra/m.css.git
  - python m.css/documentation/doxygen.py Doxyfile-mcss
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
