sudo: required

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:deadsnakes/ppa'
    packages:
      - doxygen
      - python3.8
      - python3-pip
      - python-pygments

script:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install Jinja2
  - git clone https://github.com/mosra/m.css.git
  - python3.8 m.css/documentation/doxygen.py Doxyfile-mcss
  #- doxygen Doxyfile.in

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
