matrix:
  include:
    - language: python
      dist: xenial
      sudo: false

      # Blacklist
      branches:
        only:
          - master
      python:
        - "3.6"
      addons:
        apt:
          packages:
            - libgs-dev
      before_install:
        - pip install -U pip jinja2 Pygments
      script:
        - curl http://doxygen.nl/files/doxygen-1.8.15.linux.bin.tar.gz --output doxygen.tar.gz
        - tar xfv doxygen.tar.gz
        - PATH=$PATH:doxygen-1.8.15/bin
        - export PATH
        - git clone https://github.com/mosra/m.css.git
        - python m.css/documentation/doxygen.py --debug Doxyfile-mcss
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
    
    - language: cpp
      dist: trusty
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - boost1.70
            - gzip
      script:
        - export CC=gcc-7
        - export CXX=g++-7
        - mkdir build 
        - cd build 
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j 2
        - gunzip shapes/*
        - ctest
